# ansible-role-rtorrent/tasks/main.yml
---
# -------------
# Check for supported OS
# -------------
- name: "all | ensure remote os supported"
  fail: msg="Unsupported pkg mgr. This role is depends on apt, yum, or pkgng."
  when: ansible_pkg_mgr not in ['apt', 'yum', 'pkgng']

# -------------
# Install rTorrent
# -------------
- name: "apt | ensure rTorrent present"
  become: Yes
  apt: name=rtorrent state=present update_cache=no
  when: ansible_pkg_mgr == 'apt'

- name: "yum | ensure rTorrent present"
  become: Yes
  yum: name=rtorrent state=present
  when: ansible_pkg_mgr == 'yum'

- name: "pkg | ensure rTorrent present"
  become: Yes
  pkgng: name=rtorrent state=present
  when: ansible_pkg_mgr == 'pkgng'

# -------------
# Configure rTorrent
# -------------
- name: "all | ensure torrent folders exist"
  file: path={{item}} state=directory
  with_items:
   - "{{ rtorrent_directory_watch }}"
   - "{{ rtorrent_directory_session }}"
   - "{{ rtorrent_directory_download }}"

- name: "all | ensure ~/.rtorrent.rc configured"
  template: src=rtorrent.rc.j2 dest=~/.rtorrent.rc
...
